// <auto-generated />
namespace ContosoUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class MaxLengthOnNamesandDatePickerSet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaxLengthOnNamesandDatePickerSet));
        
        string IMigrationMetadata.Id
        {
            get { return "202004152117036_MaxLengthOnNamesandDatePickerSet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
